<td>
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td>
                                                    <table width="154" height="116" border="0" cellpadding="0"
                                                           cellspacing="1" bgcolor="#CCCCCC">
                                                        <tr>
                                                            <td align="center" valign="middle" bgcolor="#FFFFFF"><a
                                                                    href="">
                                                                <img src="[field:litpic/]"
                                                                     width="187" height="150"/></a></td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td width="20">&#160;</td>
                                            </tr>
                                            <tr>
                                                <td height="25" align="center"><a href="">[field:title/]</a></td>
                                                <td width="20">&#160;</td>
                                            </tr>
                                        </table>
                                        <table width="10" height="10" border="0" cellpadding="0" cellspacing="0">
                                            <tr>
                                                <td></td>
                                            </tr>
                                        </table>
                                    </td>