{dede:noteinfo notename="ª€µ∆≤•÷÷" channelid="1" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.hzyongxingsi.com/web-huideng.asp?classid=10&x=8{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="news-list">
   <ul>{/dede:areastart}
    {dede:areaend}<table width=366{/dede:areaend}
{/dede:listrule}
