{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}편르{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}편르</div>
  <IMG alt="" src="/uploads/allimg/c130831/13M934JC5320-1E49.jpg" onload="&#106avascript:if(this.width>740)this.width=740" border=undefined></div>
 </div>
 </div>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130831/13M934JC5320-1E49.jpg{/dede:field}
