<?php
$z[0]=Array("global","",773,798);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channelartlist","\r\n				<li{dede:field.currentstyle/}>\r\n					<a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a>\r\n					<dl class=\"submenu\">\r\n						{dede:channel type='son' noself='yes'} \r\n						<dd><a href=\"[field:typelink/]\">[field:typename/]</a> </dd>\r\n						{/dede:channel} \r\n					</dl>\r\n				</li>\r\n				",836,1227);
$z[1][4]['typeid']="top";
$z[1][4]['row']="8";
$z[1][4]['currentstyle']="xz";

?>