<?php
$z[0]=Array("global","",185,217);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",533,565);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",735,767);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1134,1159);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1172,1197);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","-->\r\n    <!--<li><a href='[field:typeurl/]'>[field:typename/]</a></li>-->\r\n    <!--",1230,1433);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='xz'><a href='~typelink~'>~typename~</a></li>";
$z[6]=Array("global","",1577,1602);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channel","\r\n            <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n            ",1636,1841);
$z[7][4]['type']="top";
$z[7][4]['row']="10";
$z[7][4]['currentstyle']="<li class='xz'><a href='~typelink~'>~typename~</a></li>";

?>