<?php
$z[0]=Array("global","",100,132);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",436,468);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",605,637);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",948,973);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n    <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n    ",999,1188);
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li class='xz'><a href='~typelink~'>~typename~</a></li>";

?>