<?php
$z[0]=Array("channel","\r\n       <li><a href='[field:typelink/]' target=\"_blank\"> [field:typename/] </a></li>\r\n       ",172,417);
$z[0][4]['row']="9";
$z[0][4]['type']="son";
$z[0][4]['currentstyle']="<li style=";
$z[0][4]['background:#d6d3c9;color:#990033;"><a href']="~typelink~";
$z[0][4]['>~typename~</a></li>"']="";
$z[1]=Array("global","",556,588);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",708,740);
$z[2][4]['name']="cfg_templets_skin";

?>