<?php
$z[0]=Array("field","",255,278);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",324,382);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",421,450);
$z[2][4]['name']="keywords";
$z[3]=Array("global","",469,501);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",568,600);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",1121,1158);
$z[5][4]['filename']="header.htm";
$z[6]=Array("global","",1228,1260);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("field","",1405,1464);
$z[7][4]['name']="typename";
$z[7][4]['function']="GetTypeName£¨@me£©";
$z[8]=Array("list","\r\n         <tr>\r\n             <td>[field:pubdate function=strftime(\"%Y-%m-%d\",\"@me\")/]</td>\r\n             <td>[field:title/]</td>\r\n             <td>[field:jkje/]</td>\r\n             <td>[field:ytdd /]</td>\r\n             <td>[field:hxw /]</td>\r\n         </tr>\r\n         ",2454,2759);
$z[8][4]['pagesize']="20";
$z[9]=Array("pagelist","",2863,2922);
$z[9][4]['listitem']="index,end,pre,next";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2994,3031);
$z[10][4]['filename']="footer.htm";

?>